config/routes.rb
Rails.application.routes.draw do
  root to: "cruds#index"
  resources :cruds
end

app/models/crud.rb
class Crud < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cruds_controller.rb
class CrudsController < ApplicationController
  before_action :set_crud, only: [:show, :edit, :update, :destroy]

  # GET /cruds
  # GET /cruds.json
  def index
    @cruds = Crud.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cruds }
    end
  end

  # GET /cruds/1
  # GET /cruds/1.json
  def show
    @crud = Crud.find(params[:id])

    respond_to do |format|
      format.json { render json: @crud }
    end
  end

  # GET /cruds/new
  def new
    @crud = Crud.new

    respond_to do |format|
      format.json { render json: @crud }
    end
  end

  # POST /cruds
  # POST /cruds.json
  def create
    @crud = Crud.new(crud_params)

    respond_to do |format|
      if @crud.save
        format.json { render :show, status: :created, location: @crud }
      else
        format.json { render json: @crud.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cruds/1
  # PATCH/PUT /cruds/1.json
  def update
    respond_to do |format|
      if @crud.update(crud_params)
        format.json { render :show, status: :ok, location: @crud }
      else
        format.json { render json: @crud.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cruds/1
  # DELETE /cruds/1.json
  def destroy
    @crud.destroy
    respond_to do |format|
      
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crud
      @crud = Crud.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crud_params
      params[:crud]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cruds_helper.rb
module CrudsHelper
end

app/views/cruds/_form.html.erb
<%= form_for(@crud) do |f| %>
  <% if @crud.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@crud.errors.count, "error") %> prohibited this crud from being saved:</h2>

      <ul>
      <% @crud.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cruds/edit.html.erb
<h1>Editing crud</h1>

<%= render 'form' %>

<%= link_to 'Show', @crud %> |
<%= link_to 'Back', cruds_path %>

app/views/cruds/index.html.erb
<h1>Listing cruds</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cruds.each do |crud| %>
      <tr>
        <td><%= link_to 'Show', crud %></td>
        <td><%= link_to 'Edit', edit_crud_path(crud) %></td>
        <td><%= link_to 'Destroy', crud, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crud', new_crud_path %>

app/views/cruds/new.html.erb
<h1>New crud</h1>

<%= render 'form' %>

<%= link_to 'Back', cruds_path %>

app/views/cruds/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_crud_path(@crud) %> |
<%= link_to 'Back', cruds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestEmberRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>